import '@/styles/globals.css'

import { Inter } from 'next/font/google'

import { Navigation } from '@/components/navigation'

import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body className={inter.className}>
        <Providers>
          <div className='grid'>
            <Navigation />
            <main className='grid w-full gap-2 px-5 pt-16'>{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
